baseURL = "https://doleyhenderson.com/"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
defaultContentLanguage = "en"
theme = "hugo-scroll"

# The "title" of your website
title = "Doley Henderson - Writer of Fiction & Creative Nonfiction"

[params]
    copyright = "Â© 2025 Doley Henderson"
    description = "Writer of Fiction & Creative Nonfiction"

    # Should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"

    # Used for the structured data templates
    # See https://gohugo.io/templates/internal#twitter-cards
    title = "Doley Henderson - Writer of Fiction & Creative Nonfiction"
    images = ["images/cover-image.jpg"]

    hidedesignbyline = true

    [params.meta]
        keywords = "some, keywords, for, seo, you, know, google, duckduckgo, and, such"
